auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    instance_addr: 0.0.0.0
    kvstore:
      store: inmemory

query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

# Limits config
limits_config:
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  ingestion_rate_mb: 16
  ingestion_burst_size_mb: 24
  per_stream_rate_limit: 512M
  per_stream_rate_limit_burst: 1024M

# Chunk store config
chunk_store_config:
  max_look_back_period: 0s

# Table manager config
table_manager:
  retention_deletes_enabled: false
  retention_period: 0s

# Compactor config
compactor:
  working_directory: /loki/boltdb-shipper-compactor
  shared_store: filesystem
