spring:
  config:
    import: optional:file:.env[.properties]

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/database}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:1234}
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}


kis:
  app-key: ${KS_APP_KEY}
  app-secret: ${KS_APP_SECRET}
  account-number: ${KS_ACCOUNT_NUMBER}
  account-product-code: ${KS_ACCOUNT_PRODUCT_CODE}