spring:
  application:
    name: session
  profiles:
    active: dev

  jackson:
    property-naming-strategy: SNAKE_CASE
    serialization:
      write-dates-as-timestamps: false
      write-dates-with-zone-id: false
    deserialization:
      fail-on-unknown-properties: false
    default-property-inclusion: non_null

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        highlight_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics,env,configprops
      base-path: /actuator
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}
      environment: ${spring.profiles.active:default}
    distribution:
      percentiles-histogram:
        http.server.requests: true
        jvm.memory.used: true
        process.cpu.usage: true
      percentiles:
        http.server.requests: 0.5,0.95,0.99
        jvm.memory.used: 0.5,0.95,0.99
        process.cpu.usage: 0.5,0.95,0.99

# Logging configuration for APM
logging:
  level:
    root: INFO
    com.hsu_mafia.motoo: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Custom metrics for APM
management.metrics.enable:
  jvm: true
  process: true
  system: true
  http: true
  tomcat: true
  hikaricp: true

kis:
  grant-type: client_credentials
  scope: oob
  token-expiration-minutes: 59
