spring:

  config:
    import: optional:file:.env[.properties]

  application:
    name: session

  datasource:
    url: jdbc:postgresql://localhost:5432/database
    username: sa
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        highlight_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

    redis:
      host: redis
      port: 6379

ks:
  app-key: ${KS_APP_KEY}
  app-secret: ${KS_APP_SECRET}
  account-number: ${KS_ACCOUNT_NUMBER}
  account-product-code: ${KS_ACCOUNT_PRODUCT_CODE}
  grant-type: client_credentials
  scope: oob
  base-url: https://openapi.koreainvestment.com:9443
  sandbox-url: https://openapivts.koreainvestment.com:29443
  token-expiration-minutes: 59
