global:
  scrape_interval: 15s
  evaluation_interval: 15s

  external_labels:
    monitor: 'docker-host-alpha'

remote_write:
  - url: "http://localhost:9090/api/v1/write"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [
        'prometheus:9090',
        'host.docker.internal:9090'
      ]

  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: [
         'cadvisor:8081'
      ]

  - job_name: 'pushgateway'
    scrape_interval: 10s
    honor_labels: true
    static_configs:
      - targets: [
        'host.docker.internal:9091'
      ]

  - job_name: 'postgres-exporter'
    static_configs:
      - targets: [
        'postgres-exporter:9187'
      ]

  - job_name: 'node-exporter'
    static_configs:
      - targets: [
        'node-exporter:9100'
      ]
  
  - job_name: 'redis-exporter'
    static_configs:
      - targets: [
        'redis-exporter:9121'
      ]

  - job_name: 'spring'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [
        'backend:8080'
      ]

  - job_name: 'k6'
    static_configs:
      - targets: [
        'k6:6565'
      ]


alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: [
          "alertmanager:9093"
        ]