server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Spring Boot 애플리케이션 로그
  - job_name: spring-boot-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: spring-boot
          __path__: /logs/*.log

  # 에러 레벨별 로그 수집 (선택사항)
  - job_name: spring-boot-error-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: spring-boot-error
          level: error
          __path__: /logs/*error*.log

  # 시스템 로그 수집 (선택사항)
  - job_name: system-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: system
          __path__: /var/log/*.log

  # JSON 형태의 로그 파일 처리 예시
  - job_name: json-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: json-app
          __path__: /logs/*.json
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: message
            service: service
      - timestamp:
          source: timestamp
          format: RFC3339
      - labels:
          level:
          service:

  # 멀티라인 로그 처리 (스택 트레이스 등)
  - job_name: multiline-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: multiline-app
          __path__: /logs/application*.log
    pipeline_stages:
      - multiline:
          firstline: '^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}'
          max_wait_time: 3s

  # PostgreSQL 로그 수집
  - job_name: postgres-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: postgres
          __path__: /logs/postgres/*.log

  # Redis 로그 수집
  - job_name: redis-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: redis
          __path__: /logs/redis/*.log
